server:
  port : 8080
spring:
  datasource:
    url: jdbc:mysql://wscalendardb.csqfm7ao5z48.ap-northeast-2.rds.amazonaws.com:3306/wscalendardb?useSSL=false
    username: admin
    password: Ws12345!
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
